### ISSUE TITLE
Incorrect installation instructions

### ISSUE THREAD

**Issue by sjdrc** [lhk/darknet_wrapper#3]
Hey, thanks for the wrapper.

I needed to copy the files from ```darknet/include``` and ```darknet/examples``` into the ```darknet_wrapper/darknet/src``` folder to get the library to compile. I guess either pjreddie has reorganised some files or your makefile is linking to some object files that are not needed.

After doing this and attempting to compile the wrapper, I get the error:
```
/home/sebastien/cpp-darknet-wrapper/darknet_wrapper/darknet/libdarknet.so: undefined reference to `run_segmenter'
/home/sebastien/cpp-darknet-wrapper/darknet_wrapper/darknet/libdarknet.so: undefined reference to `make_lstm_layer'
```

Any ideas on how to proceed?

**Comment by lhk** [comment]
I'm very sorry.
I checked the installation against a local clone of the darknet repo - and broke compatibility with the latest commits.

I've updated the code and checked again.
This time I did a completely new clone of the darknet repo and this repo. Then applying the steps from the Readme.
It works for me.
